# Generated by Django 5.2.8 on 2025-11-10 18:56

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agenda", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Etiqueta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "verbose_name_plural": "Etiquetas",
            },
        ),
        migrations.AlterModelOptions(
            name="contacto",
            options={"ordering": ["nombre"]},
        ),
        migrations.RemoveField(
            model_name="contacto",
            name="correo",
        ),
        migrations.RemoveField(
            model_name="contacto",
            name="direccion",
        ),
        migrations.AddField(
            model_name="contacto",
            name="creado_en",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contacto",
            name="email",
            field=models.EmailField(
                default="noemail@mail.com",
                max_length=254,
                unique=True,
                validators=[django.core.validators.EmailValidator()],
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="contacto",
            name="telefono",
            field=models.CharField(
                max_length=15,
                validators=[
                    django.core.validators.RegexValidator(
                        message="El número debe tener entre 7 y 15 dígitos y puede iniciar con +.",
                        regex="^\\+?\\d{7,15}$",
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="contacto",
            name="etiquetas",
            field=models.ManyToManyField(blank=True, to="agenda.etiqueta"),
        ),
    ]
