# Generated by Django 5.2.8 on 2025-11-13 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agenda", "0002_etiqueta_alter_contacto_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contacto",
            old_name="email",
            new_name="correo",
        ),
        migrations.AddField(
            model_name="contacto",
            name="direccion",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
